# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='loan_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_loanaccount', to='micro_admin.LoanAccount'),
        ),
    ]
