# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0002_payments_loan_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposits',
            name='total_withdrawal_amount_interest',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposits',
            name='total_withdrawal_amount_principle',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='fixed_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_fixed_deposit', to='micro_admin.FixedDeposits'),
        ),
        migrations.AddField(
            model_name='payments',
            name='recurring_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_recurring_deposit', to='micro_admin.RecurringDeposits'),
        ),
        migrations.AddField(
            model_name='receipts',
            name='fixed_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciept_fixed_deposit', to='micro_admin.FixedDeposits'),
        ),
        migrations.AddField(
            model_name='receipts',
            name='recurring_deposit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciept_recurring_deposit', to='micro_admin.RecurringDeposits'),
        ),
        migrations.AddField(
            model_name='recurringdeposits',
            name='number_of_payments',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recurringdeposits',
            name='total_withdrawal_amount_interest',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='recurringdeposits',
            name='total_withdrawal_amount_principle',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposits',
            name='status',
            field=models.CharField(choices=[(b'Opened', b'Opened'), (b'Paid', b'Paid'), (b'Closed', b'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringdeposits',
            name='status',
            field=models.CharField(choices=[(b'Opened', b'Opened'), (b'Paid', b'Paid'), (b'Closed', b'Closed')], max_length=20),
        ),
    ]
