# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0004_clientbranch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientBranch',
            new_name='ClientBranchTransfer',
        ),
    ]
