# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0006_auto_20160708_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposits',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Paid', 'Paid'), ('Closed', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringdeposits',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Paid', 'Paid'), ('Closed', 'Closed')], max_length=20),
        ),
    ]
