# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0009_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('branch_manager', 'Can manage all accounts under his/her branch.'), ('content_manager', 'Can add, edit, delete content.'))},
        ),
    ]
