# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0011_groupmemberloanaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmemberloanaccount',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Withdrawn', 'Withdrawn'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
