# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0012_groupmemberloanaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmemberloanaccount',
            name='loan_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
