# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0013_groupmemberloanaccount_loan_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmemberloanaccount',
            name='interest_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Declining', 'Declining')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
