# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0014_groupmemberloanaccount_interest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmemberloanaccount',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
