# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0015_groupmemberloanaccount_annual_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmemberloanaccount',
            name='account_no',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
