# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0017_auto_20160823_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepaymentEvery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
