# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_admin', '0018_loanrepaymentevery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('branch_manager', 'Can manage all accounts under his/her branch.'),)},
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('Loans', 'Loans'), ('TravellingAllowance', 'TravellingAllowance'), ('Paymentofsalary', 'Paymentofsalary'), ('PrintingCharges', 'PrintingCharges'), ('StationaryCharges', 'StationaryCharges'), ('OtherCharges', 'OtherCharges'), ('SavingsWithdrawal', 'SavingsWithdrawal'), ('FixedWithdrawal', 'Fixed Deposit Withdrawal'), ('RecurringWithdrawal', 'Recurring Deposit Withdrawal')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
